-- Run any SQL in a Macro
{% macro citi_bikes_csv_format() %}
    CREATE OR REPLACE FILE FORMAT DBT_RAW.CITI_BIKES.CSV_STAR
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
	FIELD_DELIMITER = ','
	RECORD_DELIMITER = '\n'
    SKIP_HEADER = 0
	FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
	TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	ESCAPE = 'NONE'
	ESCAPE_UNENCLOSED_FIELD = '\134'
    DATE_FORMAT = 'AUTO'
	TIMESTAMP_FORMAT = 'AUTO'
	NULL_IF = ('');
{% endmacro %}